### ISSUE TITLE
Update document snapshots incrementally 

### ISSUE THREAD

**Issue by NTaylorMullen** [protobuflab/protobuf-langserver#8]
LSP enabled clients will send text document change events to LSP servers. We need to consume those change events and update our workspace manager.

This will end up being 90% the same as https://github.com/aspnet/Razor.VSCode/blob/master/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs

**Comment by ryanbrandenburg** [comment]
https://github.com/protobuflab/protobuf-langserver/commit/daf42e0da46f498bca6945fbb34f5178414e1321
