### ISSUE TITLE
Initialize workspace manager with state of the world

### ISSUE THREAD

**Issue by NTaylorMullen** [protobuflab/protobuf-langserver#9]
Proto files depend on others and the existence of files impact things like completion, errors etc. Therefore, we need to initialize our workspace manager with the current state of the world so our workspace has knowledge of every proto file, even if it's not open.

**Comment by ryanbrandenburg** [comment]
https://github.com/protobuflab/protobuf-langserver/commit/a64fbb2eee89962f4c4582181a526dbbc3e279e0
